### PR TITLE
Use tox for virtualenv setup

### PR DESCRIPTION
**Pull request by iranzo**
Use python's tox for virtual environment setup and execution

### CODE REVIEW

**Comment by ghost** [comment]
@iranzo 🙄🙄🙄🙄

**Comment by SpEcHiDe** [comment]
But Why? 😅🤔🤔

**Comment by ghost** [comment]
@SpEcHiDe wot is dis 🙄

**Comment by iranzo** [comment]
> But Why?

Because it avoids the 'virtualenv' creation manually and error-prone pip install if done outside the virtual env, and automates the repeatability of the deployment.

https://tox.readthedocs.io/en/latest/

**Pull request closed without merging**
